#!/bin/bash
#timer timeout 0 every 1
log ${rundir}/log_nvt_${system}.dat append
 
units ${units}
atom_style atomic
 
if "${restart_from} == data" then "read_data ${data_file}"
if "${restart_from} == data" then "reset_timestep 0"
if "${restart_from} == continuation" then "read_restart ${rundir}/restart_nvt_${system}.*"
 
mass 1 208.9804
pair_style ${pair_style}
pair_coeff ${pair_coeff}
 
neighbor 2.0 bin
neigh_modify every 1 delay 0 check yes
 
variable Nfreq equal 100
variable Nprint equal 100
variable Nevery equal 100
variable Nrepeat equal ${Nfreq}/${Nevery}
variable Ndump equal 100
variable nAtoms equal atoms
variable P equal 1.0 
variable Tdamp equal $(100.0*dt)
variable Thot equal 800.0
variable Tfinal equal 300.0
variable N_equillibrate_liquid equal 20000 #20 ps
variable N_cooling equal 30000 #30 ps
variable N_equillibrate_amorphous equal 30000
group bismuth type 1

timestep 0.001 #1fs

compute T all temp
fix TempAve all ave/time ${Nevery} ${Nrepeat} ${Nfreq} c_T
 
variable P equal press
fix PressAve all ave/time ${Nevery} ${Nrepeat} ${Nfreq} v_P
 
variable v equal vol
fix vAve all ave/time ${Nevery} ${Nrepeat} ${Nfreq} v_v
 
compute PE all pe pair
fix PEAve all ave/time ${Nevery} ${Nrepeat} ${Nfreq} c_PE
compute PEa all pe/atom pair
 
compute MSD all msd #computed relative to initial positions
 
thermo_style custom step cpu temp f_TempAve press f_PressAve f_PEAve vol f_vAve c_MSD[4]
thermo_modify flush yes
 
thermo ${Nfreq}

dump 1 all custom ${Ndump} ${rundir}/NVT/dump_custom.${system}.*.dat id type x y z fx fy fz c_PEa
 
restart ${Ndump} ${rundir}/restart/restart_nvt_${system}.*

# -------------------- thermostat & ramps ---------------------------
velocity all create ${Thot} 123456 mom yes rot yes dist gaussian
velocity all zero linear

run 0

fix             nvtAnneal all nvt temp ${Thot} ${Thot} ${Tdamp}
run             ${N_equillibrate_liquid}
unfix           nvtAnneal

fix             nvtCool all nvt temp ${Thot} ${Tfinal} ${Tdamp}
run             ${N_cooling}
unfix           nvtCool

fix             nvtfinalanneal all nvt temp ${Tfinal} ${Tfinal} ${Tdamp}
run             ${N_equillibrate_amorphous}
unfix           nvtfinalanneal

# # -------------------- final relax / output ---------------------------
# thresholds: energy_tol = 2.7e-4 eV ; force_tol = 2.0e-3 eV/A
min_style cg
minimize        0 1.0e-5 10000 100000

# Write Data
write_data ${rundir}/out_data_quench_${system}